name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: k8s-deployment-crendential
  - name: terraform_version
    value: "0.13.3"
  - name: bucketName
    value: tf-artifact-quyennv
  - name: backendkey
    value: tf/demo-k8s/state.tfstate

parameters:
  - name: Action
    displayName: Action
    type: string
    default: "Deployment"
    values:
      - Deployment
      - Destroy
stages:
  - stage: terraform_infra_deployment
    condition: ne('${{parameters.Action}}', 'Destroy')
    jobs:
      - job: deployment_infa
        displayName: "deployment the infra"
        steps:
          - task: TerraformInstaller@0
            displayName: "install"
            inputs:
              terraformVersion: "$(terraform_version)"

          - task: TerraformTaskV1@0
            displayName: "terraform init"
            inputs:
              provider: "aws"
              command: "init"
              backendServiceAWS: "aws-apsoutheast"
              backendAWSBucketName: "$(bucketName)"
              backendAWSKey: "$(backendkey)"

          - task: TerraformTaskV1@0
            displayName: "source validate"
            inputs:
              provider: "aws"
              command: "validate"

          - task: TerraformTaskV1@0
            displayName: "Terraform : plan"
            inputs:
              provider: "aws"
              command: "plan"
              commandOptions: '-var "access_key=$(access_key)" -var "secret_key=$(secret_key)" -out demo.tfplan'
              environmentServiceNameAWS: "aws-apsoutheast"

          - task: TerraformTaskV1@0
            displayName: "Terraform : apply"
            inputs:
              provider: "aws"
              command: "apply"
              commandOptions: "-input=false -auto-approve demo.tfplan"
              environmentServiceNameAWS: "aws-apsoutheast"

  - stage: terraform_destroy
    condition: contains('${{ parameters.Action }}', 'Destroy')
    jobs:
      - job: destroy_infra
        displayName: "Destroy the infra"
        steps:
          - task: TerraformInstaller@0
            displayName: "install"
            inputs:
              terraformVersion: "$(terraform_version)"

          - task: TerraformTaskV1@0
            displayName: "terraform init"
            inputs:
              provider: "aws"
              command: "init"
              backendServiceAWS: "aws-apsoutheast"
              backendAWSBucketName: "$(bucketName)"
              backendAWSKey: "$(backendkey)"
          - task: TerraformTaskV1@0
            displayName: "Terraform : destroy"
            inputs:
              provider: aws
              command: destroy
              environmentServiceNameAWS: "aws-apsoutheast"
              backendServiceAWS: "aws-apsoutheast"
              backendAWSBucketName: "$(bucketName)"
              backendAWSKey: "$(backendkey)"
              commandOptions: '-input=false -auto-approve -var "access_key=$(access_key)" -var "secret_key=$(secret_key)"'
